from django.urls import path
from app.views import *
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
# from knox import views as knox_views
from app import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('Signup/', SignupAPI.as_view(), name='auth_register'),
    path('CreateProfile/', CreateProfile.as_view(), name='Create_Profile'), 
    path('Login/', LoginAPI.as_view(), name='app-login'),
    path('GuestLogin/', GuestLoginAPI.as_view(), name='app-login'),
    path('ForgotPassword/', ForgotPasswordAPI.as_view(), name='Forgot-Password'),
    path('ResetPassword/', ResetPasswordAppAPI.as_view(), name='Reset-Password'),
    path('ResetPwdTmpDirecti/', ResetPasswordDirectAPI.as_view(), name='Reset-Redirect'),#ResetPasswordAPI
    path('ResetPwdTemplate/', ResetPasswordAPI, name='Reset-Redirect'),#ResetPasswordAPI
    path('PwdResetSuccess/', PwdResetSuccess.as_view(), name='Pwd-Reset-Success'),
    path('EditProfile/', EditProfileAPI.as_view(), name='Edit-Profile'),
    path('Notifications/', NotificationsAPI.as_view(), name='Notification'),
    path('NotificationsList/', NotificationsListAPI.as_view(), name='Notification-List'),
    path('DeleteAccount/', DeleteAccountAPI.as_view(), name='Delete-Account'),
    path('TermAndPolicy/', TermAndPolicyAPI.as_view(), name='Term-Policy'),
    path('ChangePassword/', ChangePasswordAPI.as_view(), name='Change-Password'),
    path('RequestAudio/', RequestAudioAPI.as_view(), name='Request-Audio'),
    path('ContactUs/', ContactUsAPI.as_view(), name='Contact-Us'),
    path('ReportPodcast/', ReportPodcastAPI.as_view(), name='Contact-Us'),
    path('MarkFavourite/', MarkFavouriteAPI.as_view(), name='Mark-Favourite'),
    path('MarkUnFavourite/', MarkUnFavouriteAPI.as_view(), name='Mark-UnFavourite'),
    path('Favourites/', FavouritesAPI.as_view(), name='All-Favourites'),
    path('Friends/', FriendsAPI.as_view(), name='All-Friends'),
    path('LikeItem/', LikeItemAPI.as_view(), name='Like-Item'),
    path('DisLikeItem/', DisLikeItemAPI.as_view(), name='Like-Item'),
    path('InviteDetails/', InviteDetailsAPI.as_view(), name='Invite-Details'),
    path('Invite/', InviteAPI.as_view(), name='Send-Invite'),
    path('LogOut/', LogOutAPI.as_view(), name='Log-Out'),
    path('TVShowSeasons/', TVShowSeasonsAPI.as_view(), name='TVShow-Seasons'),
    path('TVShowEpisodeDetail/', TVShowEpisodeDetailAPI.as_view(), name='TVShow-Episode-Detail'),
    path('TVShowEpisodes/', TVShowEpisodeAPI.as_view(), name='TVShow-Episodes'),
    path('ItemDetails/', ItemDetailsAPI.as_view(), name='Item-Details'),
    path('FollowUser/', FollowUserAPI.as_view(), name='Follow-User'),
    path('UnFollowUser/', UnFollowUserAPI.as_view(), name='Follow-User'),
    path('GetComments/', GetCommentsAPI.as_view(), name='Get-Comments'),
    path('Comment/', CommentAPI.as_view(), name='Add-Comment'),
    path('GetCategories/', GetCategoriesAPI.as_view(), name='Get-Categories'),
    path('UserProfile/', UserProfileAPI.as_view(), name='User-Profile'),
    path('HomeScreen/', HomeScreenAPI.as_view(), name='Home-Screen'),
    path('SearchHomeScreen/', SearchHomeScreenAPI.as_view(), name='SearchHome-Screen'),
    path('Transaction/', TransactionAPI.as_view(), name='Transaction'),
    #path('api/logout/', knox_views.LogoutView.as_view(), name='logout'),
    #path('api/logoutall/', knox_views.LogoutAllView.as_view(), name='logoutall'),
    path('GetItemsCategoryWise/', GetItemsCategoryWiseAPI.as_view(), name='Items-Category-Wise'),
    path('delete/<int:id>',views.delete),
    path('deleteseason/<int:id>',views.deleteseason),
    path('deleteepisode/<int:id>',views.deleteepisode),
    path('index/',views.index,name='index'),
    path('user/',views.usermanage,name='user'),
    path('podcast/',views.views,name='podcast'),
    path('season/',views.seasons,name='season'),
    path('episode/',views.episodes,name='episode'),
    path('report/',views.ReportManage,name='report'),
    path('request/',views.requestaudio,name='request'),
    path('add/',views.AddPodcast,name='add'),
    path('addseason/',views.AddSeason,name='addseson'),
    path('addepisode/',views.AddEpisode,name='addepisode'),
    path('view/',views.viewuser,name='view'),
    path('viewrequest/',views.viewrequest,name='viewrequest'),
    path('viewreport/',views.viewreport,name='viewreport'),
    path('logins/',views.Login,name='Login'),
    path('accounts/login/',views.Login,name='Login'),
    path('forgot/',views.ForgotPassword,name='forgot'),
    path('change/<int:id>/',views.ChangePassword,name='change'),
    path('adminpodcast',PodcastManagementAPI.as_view(),name='adminpodcast'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]
