# Generated by Django 3.0 on 2022-02-28 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('Business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='BusineesProfileImages')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('BusinessImages', models.ImageField(blank=True, null=True, upload_to='BusineesImages')),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('Contact', models.BigIntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('TennisCourts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HostMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Time', models.TimeField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('SelectMode', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Private', max_length=200)),
                ('Status', models.CharField(choices=[('Initiated', 'Initiated'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Initiated', max_length=200)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='UserProfileImages')),
                ('FirstName', models.CharField(blank=True, max_length=200, null=True)),
                ('LastName', models.CharField(blank=True, max_length=200, null=True)),
                ('Country', models.CharField(blank=True, max_length=200, null=True)),
                ('State', models.CharField(blank=True, max_length=200, null=True)),
                ('ZipCode', models.CharField(blank=True, max_length=6, null=True)),
                ('CPFNumber', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('MatchesHosted', models.IntegerField(blank=True, default=0, null=True)),
                ('MatchesWon', models.IntegerField(blank=True, default=0, null=True)),
                ('MatchesPlayed', models.IntegerField(blank=True, default=0, null=True)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Team2Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('HostMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HostMatches')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Team1Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('HostMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HostMatches')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(blank=True, default=0, null=True)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('HostMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HostMatches')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team1Score', models.IntegerField(blank=True, default=0, null=True)),
                ('Team2Score', models.IntegerField(blank=True, default=0, null=True)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('HostMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HostMatches')),
            ],
        ),
        migrations.AddField(
            model_name='hostmatches',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profiles'),
        ),
        migrations.CreateModel(
            name='HostInvitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberInvited', models.BigIntegerField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('Sent', 'Sent'), ('Attend', 'Attend'), ('Decline', 'Decline')], default='Sent', max_length=200)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('HostMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HostMatches')),
                ('UserInvited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceToken', models.CharField(blank=True, max_length=250, null=True)),
                ('DeviceType', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=500)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactFromBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.CharField(blank=True, max_length=200, null=True)),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BusinessModel')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.CharField(blank=True, max_length=200, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(blank=True, max_length=200, null=True)),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BusinessModel')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200, null=True)),
                ('StartTime', models.TimeField(blank=True, null=True)),
                ('CloseTime', models.TimeField(blank=True, null=True)),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BusinessModel')),
            ],
        ),
    ]
