# Generated by Django 3.0 on 2022-03-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='BusinessImages',
            field=models.FileField(blank=True, null=True, upload_to='BusineesImages'),
        ),
    ]
