# Generated by Django 3.0 on 2022-03-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220301_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='BusinessImages',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='BusinessImages'),
        ),
    ]
