# Generated by Django 3.0 on 2022-03-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220301_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='CPFNumber',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
