# Generated by Django 3.0 on 2022-03-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_businessmodel_cpfnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessmodel',
            old_name='Business',
            new_name='User',
        ),
    ]
