# Generated by Django 3.0 on 2022-03-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220302_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='Email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
