# Generated by Django 3.0 on 2022-03-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_businessmodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmodel',
            name='Email',
        ),
    ]
