# Generated by Django 3.0 on 2022-03-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_businessmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='ZipCode',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
