# Generated by Django 3.0 on 2022-03-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220308_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='latitude',
            field=models.CharField(default='25.2048', max_length=500),
        ),
        migrations.AddField(
            model_name='profiles',
            name='longitude',
            field=models.CharField(default='55.2708', max_length=500),
        ),
    ]
