# Generated by Django 3.0 on 2022-03-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220308_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='latitude',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='longitude',
            field=models.CharField(max_length=500),
        ),
    ]
