# Generated by Django 3.0 on 2022-03-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220308_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactfrombusiness',
            old_name='Business',
            new_name='User',
        ),
    ]
