# Generated by Django 3.0 on 2022-03-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220308_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='latitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='longitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
