# Generated by Django 3.0 on 2022-03-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220308_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='latitude',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='longitude',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
