# Generated by Django 3.0 on 2022-03-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220310_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='latitude',
            field=models.FloatField(max_length=500),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='longitude',
            field=models.FloatField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
