# Generated by Django 3.0 on 2022-03-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20220317_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='City',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
