# Generated by Django 3.0 on 2022-03-21 07:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_profiles_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Sent', 'Sent'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='Sent', max_length=200)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver', to='app.Profiles')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='app.Profiles')),
            ],
        ),
    ]
