# Generated by Django 3.0 on 2022-03-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_friendrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='CPFNumber',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='CPFNumber',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
