# Generated by Django 3.2.7 on 2021-11-12 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=400)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryGunType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GunName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryHolsterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HolsterName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TermAndPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Policy', models.CharField(max_length=300)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('OtherUser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user13', to=settings.AUTH_USER_MODEL)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user12', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstBeep', models.TimeField()),
                ('DrawTime', models.TimeField()),
                ('ShotTime', models.TimeField()),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('Gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.primaryguntype')),
                ('Holster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.primaryholstertype')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParTime', models.FloatField(blank=True, default=0, null=True)),
                ('DrawTime', models.FloatField(blank=True, default=0, null=True)),
                ('ShotTime', models.FloatField(blank=True, default=0, null=True)),
                ('DateOfRecord', models.DateTimeField(default=django.utils.timezone.now)),
                ('Gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user10', to='app.primaryguntype')),
                ('Holster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user11', to='app.primaryholstertype')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user9', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileImage', models.ImageField(upload_to='media')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Country', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsSuspended', models.BooleanField(default=False)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.primaryguntype')),
                ('Holster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.primaryholstertype')),
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Nuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InviteFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField(max_length=500)),
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstBeep', models.TimeField()),
                ('ShotTime', models.TimeField()),
                ('DrawTime', models.TimeField()),
                ('Gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.primaryguntype')),
                ('Holster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.primaryholstertype')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user34', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GunInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instructor', models.TextField()),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('OtherUser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user5', to=settings.AUTH_USER_MODEL)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceToken', models.CharField(max_length=250, unique=True)),
                ('DeviceType', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=500)),
                ('Country', models.CharField(max_length=250)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
                ('Subject', models.CharField(max_length=200)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
            ],
        ),
        migrations.CreateModel(
            name='BestTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstBeep', models.TimeField()),
                ('DrawTime', models.TimeField()),
                ('ShotTime', models.TimeField()),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('Gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.primaryguntype')),
                ('Holster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.primaryholstertype')),
            ],
        ),
    ]
