# Generated by Django 3.2.7 on 2021-11-12 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_id', models.CharField(blank=True, max_length=500, null=True)),
                ('Amount', models.CharField(blank=True, max_length=50, null=True)),
                ('Timeframe', models.CharField(blank=True, max_length=500, null=True)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user76', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
