# Generated by Django 3.2.7 on 2021-11-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
