# Generated by Django 3.2.7 on 2021-11-25 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20211123_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_id', models.CharField(blank=True, max_length=500, null=True)),
                ('SubscribedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Month', models.CharField(max_length=500)),
                ('subscriptionEndDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('PlanId', models.CharField(default='com.gi', max_length=500, primary_key=True, serialize=False)),
                ('PlanName', models.CharField(max_length=500)),
                ('PlanCost', models.IntegerField()),
                ('text', models.TextField()),
                ('Descritption', models.CharField(max_length=500)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='subscribeduser',
            name='Subscription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscribeduser',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
