# Generated by Django 3.2.7 on 2021-12-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211125_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeduser',
            name='subscriptionEndDate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
