# Generated by Django 3.2.7 on 2021-12-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_subscribeduser_subscribeddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeduser',
            name='Month',
        ),
    ]
