# Generated by Django 3.2.7 on 2021-12-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211206_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribeduser',
            old_name='Date',
            new_name='SubscribedDate',
        ),
    ]
