# Generated by Django 3.2.7 on 2021-12-10 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_subscribeduser_subscribeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeduser',
            name='SubscribedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
