# Generated by Django 3.2.7 on 2021-12-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_subscribeduser_subscribeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeduser',
            name='SubscribedDate',
            field=models.DateField(),
        ),
    ]
