# Generated by Django 3.2.7 on 2021-12-10 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_alter_subscribeduser_subscribeddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeduser',
            name='SubscribedDate',
        ),
        migrations.CreateModel(
            name='SubscribedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('SubscribedDate', models.DateField()),
                ('SubscriptionEndDate', models.CharField(blank=True, max_length=500, null=True)),
                ('Subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subscriptionplan')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
