# Generated by Django 3.2.7 on 2021-12-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_subscribeduser_suscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribeduser',
            old_name='Suscribed',
            new_name='Subscribed',
        ),
    ]
