# Generated by Django 3.2.7 on 2021-12-20 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0026_rename_suscribed_subscribeduser_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
                ('Subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GunInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instruction', models.TextField(max_length=400)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('InviteDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user7', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='media')),
                ('FirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('LastName', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Country', models.CharField(blank=True, max_length=300, null=True)),
                ('State', models.CharField(blank=True, max_length=400, null=True)),
                ('Gun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.primaryguntype')),
                ('Holster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.primaryholstertype')),
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubscribedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('PlanId', models.CharField(default='com.gi', max_length=500, primary_key=True, serialize=False)),
                ('PlanName', models.CharField(max_length=500)),
                ('PlanCost', models.IntegerField()),
                ('text', models.TextField()),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SuspendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OtherReasonText', models.CharField(blank=True, max_length=1000, null=True)),
                ('DateSuspended', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SuspendReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='media')),
                ('FirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('LastName', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Country', models.CharField(blank=True, max_length=300, null=True)),
                ('State', models.CharField(blank=True, max_length=400, null=True)),
                ('IsSuspended', models.BooleanField(default=False)),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('CurrentPlanId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subscriptionplan')),
                ('Gun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.primaryguntype')),
                ('Holster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.primaryholstertype')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParTime', models.FloatField(blank=True, default=0, null=True)),
                ('DrawTime', models.FloatField(blank=True, default=0, null=True)),
                ('ShotTime', models.FloatField(blank=True, default=0, null=True)),
                ('DateOfRecord', models.DateTimeField(default=django.utils.timezone.now)),
                ('Gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user110', to='app.primaryguntype')),
                ('Holster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user111', to='app.primaryholstertype')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user99hgho', to='app.userprofiles')),
            ],
        ),
        migrations.RemoveField(
            model_name='besttime',
            name='Gun',
        ),
        migrations.RemoveField(
            model_name='besttime',
            name='Holster',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='OtherUser_id',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='guninstructor',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='invitefriend',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='User_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Gun',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Holster',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='shotlog',
            name='Gun',
        ),
        migrations.RemoveField(
            model_name='shotlog',
            name='Holster',
        ),
        migrations.RemoveField(
            model_name='subscribedusers',
            name='Subscription_id',
        ),
        migrations.RemoveField(
            model_name='subscribedusers',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='usernotifications',
            name='OtherUser_id',
        ),
        migrations.RemoveField(
            model_name='usernotifications',
            name='User_id',
        ),
        migrations.RenameField(
            model_name='subscribeduser',
            old_name='Subscribed',
            new_name='SubscribedDate',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='Timeframe',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='Transaction_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='text',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscribeduser',
            name='subscriptionEndDate',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user8', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BestTime',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='GunInstructor',
        ),
        migrations.DeleteModel(
            name='InviteFriend',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ShotLog',
        ),
        migrations.DeleteModel(
            name='SubscribedUsers',
        ),
        migrations.DeleteModel(
            name='UserNotifications',
        ),
        migrations.AddField(
            model_name='suspendhistory',
            name='Reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suspendreason'),
        ),
        migrations.AddField(
            model_name='suspendhistory',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofiles'),
        ),
        migrations.AddField(
            model_name='subscribed',
            name='Subscription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subscriptions'),
        ),
        migrations.AddField(
            model_name='subscribed',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacts',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofiles'),
        ),
    ]
