# Generated by Django 4.0.5 on 2022-12-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_tms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketactivity",
            name="activity",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("statechange", "Statechange"),
                    ("assignment", "Assignment"),
                ],
                max_length=100,
                verbose_name="activity",
            ),
        ),
    ]
