# Generated by Django 4.0.5 on 2022-12-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_tms", "0002_alter_ticketactivity_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="soteria_tms.priority",
                verbose_name="priority",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="soteria_tms.ticketlabel",
                verbose_name="ticket label",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="soteria_tms.tickettype",
                verbose_name="ticket type",
            ),
        ),
    ]
