# Generated by Django 4.0.5 on 2022-08-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_orgs", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
