# Generated by Django 4.0.5 on 2022-08-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_orgs", "0004_organizationmember_organizationmemberlocation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("executive", "Executive"),
                    ("supervisor", "Supervisor"),
                    ("leader", "Leader"),
                ],
                default="client",
                max_length=30,
            ),
        ),
    ]
