# Generated by Django 4.0.5 on 2022-08-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_orgs", "0005_organizationmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="token",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
