# Generated by Django 4.0.5 on 2022-08-18 11:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("soteria", "0008_userorganization"),
        ("soteria_orgs", "0007_remove_organizationmember_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "userorganization_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="soteria.userorganization",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="last updated at"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="email address",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        null=True,
                        unique=True,
                        verbose_name="mobile number",
                    ),
                ),
                ("token", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("token_expires_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("executive", "Executive"),
                            ("supervisor", "Supervisor"),
                            ("leader", "Leader"),
                        ],
                        default="client",
                        max_length=30,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "location",
                    models.ManyToManyField(
                        blank=True,
                        through="soteria_orgs.OrganizationMemberLocation",
                        to="soteria_orgs.location",
                        verbose_name="location",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="last updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization member",
                "verbose_name_plural": "organization members",
                "db_table": "soteria_org_member",
            },
            bases=("soteria.userorganization", models.Model),
        ),
    ]
