# Generated by Django 3.2.4 on 2021-07-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emailchangecode_passwordresetcode_signupcode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proadcast',
            table='Proadcast',
        ),
        migrations.AlterModelTable(
            name='report',
            table='Report',
        ),
        migrations.AlterModelTable(
            name='requestaudio',
            table='RequestAudio',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
