# Generated by Django 3.2.4 on 2021-07-05 05:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20210705_0507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proadcast',
            new_name='Proadcastmodel',
        ),
        migrations.RenameModel(
            old_name='Report',
            new_name='Reportmodel',
        ),
        migrations.RenameModel(
            old_name='RequestAudio',
            new_name='RequestAudiomodel',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Usermodel',
        ),
    ]
