# Generated by Django 3.2.4 on 2021-07-10 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_profilemodel_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Comments', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=500)),
                ('Message', models.CharField(max_length=500)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user7', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceType', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=500)),
                ('DeviceToken', models.CharField(max_length=500)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('File', models.FileField(upload_to='upload')),
                ('Duration', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ForYou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OtherUser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user5', to=settings.AUTH_USER_MODEL)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('File', models.FileField(upload_to=None)),
                ('Duration', models.CharField(max_length=500)),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category1', to='app.categories')),
            ],
        ),
        migrations.CreateModel(
            name='LikedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='app.items')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileImage', models.ImageField(upload_to='radio')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=500)),
                ('Message', models.CharField(max_length=500)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user8', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Message', models.TextField()),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.items')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user9', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongName', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category2', to='app.categories')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user6', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NumberOfSeasons', models.IntegerField()),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item4', to='app.items')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndPlicyText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailchangecode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='user',
        ),
        migrations.DeleteModel(
            name='Proadcastmodel',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='userid',
        ),
        migrations.DeleteModel(
            name='Reportmodel',
        ),
        migrations.DeleteModel(
            name='RequestAudiomodel',
        ),
        migrations.RemoveField(
            model_name='signupcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user',
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('Item_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.items')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailChangeCode',
        ),
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
        migrations.DeleteModel(
            name='Profilemodel',
        ),
        migrations.DeleteModel(
            name='SignupCode',
        ),
        migrations.DeleteModel(
            name='Usermodel',
        ),
        migrations.AddField(
            model_name='foryou',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.items'),
        ),
        migrations.AddField(
            model_name='episodes',
            name='Item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item5', to='app.items'),
        ),
        migrations.AddField(
            model_name='episodes',
            name='Season_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='app.seasons'),
        ),
        migrations.AddField(
            model_name='comments',
            name='Item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item7', to='app.items'),
        ),
    ]
