# Generated by Django 3.2.4 on 2021-07-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210710_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='user_id',
            new_name='User_id',
        ),
    ]
