# Generated by Django 3.2.4 on 2021-07-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_user_id_devices_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='DeviceToken',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ProfileImage',
            field=models.ImageField(upload_to='UserProfileImages'),
        ),
    ]
