# Generated by Django 3.2.4 on 2021-07-12 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_auto_20210712_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='User_id',
            field=models.ForeignKey(default=53, on_delete=django.db.models.deletion.CASCADE, related_name='user0', to='auth.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
