# Generated by Django 3.2.4 on 2021-07-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210713_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='Description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='episodes',
            name='Name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='Description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
