# Generated by Django 3.2.4 on 2021-07-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210713_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DeviceType', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=500)),
                ('DeviceToken', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
