# Generated by Django 3.2.4 on 2021-07-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210714_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasons',
            name='Description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
