# Generated by Django 3.2.4 on 2021-07-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_usernotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='Name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='DeviceToken',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='DeviceToken',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
