# Generated by Django 3.2.4 on 2021-07-22 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210722_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 7, 38, 28, 644725)),
        ),
    ]
