# Generated by Django 3.2.4 on 2021-07-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210723_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 41 07/23/21 - 07:41:13'),
        ),
    ]
