# Generated by Django 3.2.4 on 2021-07-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_notifications_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 55 07/23/21 - 07:55:36'),
        ),
    ]
