# Generated by Django 3.2.4 on 2021-07-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_notifications_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 57 07/23/21 - 07:57:43'),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 57 07/23/21 - 07:57:43'),
        ),
    ]
