# Generated by Django 3.2.4 on 2021-07-23 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210723_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='DateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 27 07/23/21 - 08:27:33'),
        ),
    ]
