# Generated by Django 3.2.4 on 2021-07-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_usernotifications_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to='static_media/UserProfileImages'),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 14 07/23/21 - 09:14:39'),
        ),
    ]
