# Generated by Django 3.2.4 on 2021-07-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210723_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='ItemFiles'),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 34 07/23/21 - 09:34:05'),
        ),
    ]
