# Generated by Django 3.2.4 on 2021-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20210723_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='ArtistName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='Comments',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='Views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 06 07/29/21 - 10:06:48'),
        ),
    ]
