# Generated by Django 3.2.4 on 2021-08-03 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210729_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('action', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ram')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='UserProfileImages'),
        ),
        migrations.AddField(
            model_name='requestedaudio',
            name='FirstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestedaudio',
            name='LastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestedaudio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='UserProfileImages'),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 54 08/03/21 - 16:54:08'),
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiofile', models.FileField(upload_to='None')),
                ('descritption', models.TextField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categories')),
            ],
        ),
    ]
