# Generated by Django 3.2.4 on 2021-08-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20210803_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='requestedaudio',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 16 08/03/21 - 17:16:01'),
        ),
    ]
