# Generated by Django 3.2.4 on 2021-08-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210825_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 25 08/25/21 - 07:25:19'),
        ),
    ]
