# Generated by Django 3.2.4 on 2021-09-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20210907_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 27 09/07/21 - 05:27:13'),
        ),
    ]
