# Generated by Django 3.2.4 on 2021-09-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_usernotifications_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='FirstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='LastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 27 09/07/21 - 05:27:38'),
        ),
    ]
