# Generated by Django 3.2.4 on 2021-09-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20210907_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='FirstName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='LastName',
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 38 09/09/21 - 07:38:44'),
        ),
    ]
