# Generated by Django 3.2.4 on 2021-09-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20210909_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='FirstName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='requestedaudio',
            old_name='FirstName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='requestedaudio',
            name='LastName',
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 41 09/09/21 - 07:41:09'),
        ),
    ]
