# Generated by Django 3.2.4 on 2021-09-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20210909_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='Name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='requestedaudio',
            old_name='Name',
            new_name='FirstName',
        ),
        migrations.AddField(
            model_name='profile',
            name='LastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='LastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestedaudio',
            name='LastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='DateAdded',
            field=models.DateTimeField(default='2021 45 09/09/21 - 07:45:39'),
        ),
    ]
