# Generated by Django 4.0.4 on 2022-06-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_create_org",
            field=models.BooleanField(
                default=False, verbose_name="can user create new organization"
            ),
        ),
    ]
