# Generated by Django 4.0.4 on 2022-06-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soteria", "0002_invitationcode"),
        ("soteria", "0002_user_can_create_org"),
    ]

    operations = []
