# Generated by Django 4.0.5 on 2022-07-25 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria", "0003_merge_0002_invitationcode_0002_user_can_create_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_password_change_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date the password was changed last.",
                null=True,
                verbose_name="date of last password change",
            ),
        ),
        migrations.CreateModel(
            name="ResetPasswordTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="last updated at"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="expires at"
                    ),
                ),
                (
                    "client_ip",
                    models.CharField(
                        blank=True,
                        help_text="IP address of the request client.",
                        max_length=50,
                        null=True,
                        verbose_name="client ip",
                    ),
                ),
                (
                    "client_ua",
                    models.CharField(
                        blank=True,
                        help_text="User agent of client from request.",
                        max_length=100,
                        null=True,
                        verbose_name="client ua",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="last updated by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "reset password",
                "verbose_name_plural": "reset passwords",
                "db_table": "soteria_reset_password",
            },
        ),
    ]
