# Generated by Django 4.0.5 on 2022-07-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soteria", "0004_tenantmodelmixin_tenant_domain"),
        ("soteria", "0004_user_last_password_change_at_resetpasswordticket"),
    ]

    operations = []
