# Generated by Django 4.0.5 on 2022-07-28 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria", "0005_merge_20220725_1151"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "tenantmodelmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="soteria.tenantmodelmixin",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                ("slug", models.SlugField(blank=True, unique=True, verbose_name="slug")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=100,
                        verbose_name="status",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200, verbose_name="address")),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
                "db_table": "soteria_organization",
            },
            bases=("soteria.tenantmodelmixin",),
        ),
        migrations.AlterField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="soteria.organization",
            ),
        ),
        migrations.DeleteModel(
            name="Tenant",
        ),
    ]
