# Generated by Django 4.0.5 on 2022-08-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria", "0006_organization_alter_domain_tenant_delete_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpasswordticket",
            name="client_ua",
            field=models.CharField(
                blank=True,
                help_text="User agent of client from request.",
                max_length=500,
                null=True,
                verbose_name="client ua",
            ),
        ),
        migrations.AlterField(
            model_name="resetpasswordticket",
            name="token",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="token",
            ),
        ),
    ]
