# Generated by Django 4.0.5 on 2022-11-22 05:38

from django.conf import settings
from django.db import connection, migrations

from soteria.reports.services.template_report import create_report_templates


def add_report_template(apps, schema_editor):
    Organization = apps.get_model("soteria.Organization")
    Report = apps.get_model("soteria.Report")
    for organization in Organization.objects.all().exclude(schema_name=settings.PUBLIC_SCHEMA_NAME):
        connection.set_tenant(organization)
        if not Report.objects.filter(organization=organization.id).first():
            create_report_templates(organization.id)


class Migration(migrations.Migration):

    dependencies = [
        ('soteria', '0009_report'),
    ]

    operations = [
        migrations.RunPython(add_report_template, reverse_code=migrations.RunPython.noop),

    ]
