# Generated by Django 4.0.5 on 2022-08-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_atms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assettype",
            name="tag",
        ),
        migrations.AddField(
            model_name="asset",
            name="tag",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="tag"),
        ),
    ]
