# Generated by Django 4.0.5 on 2022-08-26 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_atms", "0002_remove_assettype_tag_asset_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="soteria_atms.tasktype",
                verbose_name="task type",
            ),
        ),
    ]
