# Generated by Django 4.0.5 on 2022-08-29 06:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_orgs", "0008_organizationmember"),
        ("soteria_atms", "0003_task_name_alter_task_task_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assign_to",
        ),
        migrations.RemoveField(
            model_name="task",
            name="form",
        ),
        migrations.RemoveField(
            model_name="task",
            name="task_type",
        ),
        migrations.AddField(
            model_name="job",
            name="assign_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="soteria_orgs.organizationmember",
                verbose_name="assign to",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="soteria_orgs.location",
                verbose_name="location",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="job",
            name="weekdays",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                blank=True,
                null=True,
                size=7,
                verbose_name="days",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
        ),
        migrations.AddField(
            model_name="task",
            name="form_submission_data",
            field=models.JSONField(blank=True, null=True, verbose_name="form submission data"),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("overdue", "Overdue"),
                ],
                default="pending",
                max_length=100,
                verbose_name="status",
            ),
        ),
        migrations.DeleteModel(
            name="TaskType",
        ),
    ]
