# Generated by Django 4.0.5 on 2022-09-12 06:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_atms", "0007_alter_asset_asset_type_floor_asset_floor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="end_at",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_recurring",
        ),
        migrations.RemoveField(
            model_name="job",
            name="schedule_at",
        ),
        migrations.RemoveField(
            model_name="job",
            name="start_at",
        ),
        migrations.AddField(
            model_name="job",
            name="duration",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Duration of one timeslot in minutes",
                null=True,
                verbose_name="duration",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="time_ranges",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TimeField(),
                blank=True,
                null=True,
                size=None,
                verbose_name="time ranges",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.CharField(blank=True, max_length=300, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="job",
            name="name",
            field=models.CharField(blank=True, max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="jobtype",
            name="description",
            field=models.CharField(blank=True, max_length=200, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="jobtype",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="name"),
        ),
    ]
