# Generated by Django 4.0.5 on 2022-09-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_atms", "0008_remove_job_end_at_remove_job_is_recurring_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end_at",
            field=models.TimeField(blank=True, null=True, verbose_name="end at"),
        ),
        migrations.AddField(
            model_name="task",
            name="start_at",
            field=models.TimeField(blank=True, null=True, verbose_name="start at"),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(blank=True, max_length=200, verbose_name="name"),
        ),
    ]
