# Generated by Django 4.0.5 on 2022-10-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_atms", "0009_task_end_at_task_start_at_alter_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="image_url",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="image url"),
        ),
    ]
