# Generated by Django 4.0.5 on 2022-10-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_atms", "0010_asset_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="date"),
        ),
    ]
