# Generated by Django 4.0.5 on 2022-10-12 11:09

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_atms", "0012_auto_20221012_0632"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(
                choices_display="WITH_GMT_OFFSET", default=None, verbose_name="timezone"
            ),
            preserve_default=False,
        ),
    ]
