# Generated by Django 4.0.5 on 2022-10-12 11:10

from django.db import migrations


def backfill_timezone(apps, schema_editor):
    Job = apps.get_model("soteria_atms.Job")
    jobs = Job.objects.all()
    for job in jobs:
        job.timezone = "Asia/Kolkata"
        job.save(update_fields=["timezone"])


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_atms", "0013_job_timezone"),
    ]

    operations = [
        migrations.RunPython(backfill_timezone, reverse_code=migrations.RunPython.noop),
    ]
