# Generated by Django 4.0.5 on 2022-10-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_atms", "0014_auto_20221012_1110"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end_at_tem",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end at"),
        ),
        migrations.AddField(
            model_name="task",
            name="start_at_tem",
            field=models.DateTimeField(blank=True, null=True, verbose_name="start at"),
        ),
    ]
