# Generated by Django 4.0.5 on 2022-10-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_atms", "0016_auto_20221013_1028"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="end_at",
        ),
        migrations.RemoveField(
            model_name="task",
            name="start_at",
        ),
    ]
