# Generated by Django 4.0.5 on 2022-10-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_atms", "0017_remove_task_date_remove_task_end_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="end_at_tem",
            new_name="end_at",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="start_at_tem",
            new_name="start_at",
        ),
    ]
