# Generated by Django 4.0.5 on 2022-11-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_atms", "0018_rename_end_at_tem_task_end_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="location_metadata",
            field=models.CharField(blank=True, max_length=100, verbose_name="location metadata"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="tag",
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name="tag"),
            preserve_default=False,
        ),
    ]
