# Generated by Django 4.0.5 on 2022-11-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soteria_atms', '0019_asset_location_metadata_alter_asset_tag'),
        ('soteria_atms', '0019_task_is_late_submission'),
    ]

    operations = [
    ]
