# Generated by Django 4.0.5 on 2022-12-05 05:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soteria_atms', '0020_merge_20221122_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='months',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=12, verbose_name='months'),
        ),
    ]
