# Generated by Django 4.0.5 on 2022-12-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soteria_atms', '0021_job_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='months',
        ),
        migrations.AddField(
            model_name='job',
            name='start_from',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2022-11-22 15:33:30.067 +0530', verbose_name='start_from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='time_scale',
            field=models.CharField(choices=[('monthly', 'monthly'), ('quaterly', 'Quaterly'), ('yearly', 'Yearly'), ('fort_nightly', 'Fort_nightly'), ('half_yearly', 'half_yearly')], default='monthly', max_length=100, verbose_name='job_schedule'),
        ),
    ]
