# Generated by Django 4.0.5 on 2022-12-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soteria_atms', '0022_remove_job_months_job_start_from_job_time_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='start_from',
            field=models.DateTimeField(db_index=True, verbose_name='start_from'),
        ),
        migrations.AlterField(
            model_name='job',
            name='time_scale',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quaterly', 'Quaterly'), ('yearly', 'Yearly'), ('fort_nightly', 'Fort_nightly'), ('half_yearly', 'Half_yearly')], default='daily', max_length=100, verbose_name='time_scale'),
        ),
    ]
