# Generated by Django 4.0.5 on 2022-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soteria_atms', '0023_alter_job_start_from_alter_job_time_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='start_from',
        ),
        migrations.AddField(
            model_name='job',
            name='end_at',
            field=models.DateTimeField(db_index=True, default='2022-11-12 23:50:00.000 +0530', verbose_name='end_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='start_at',
            field=models.DateTimeField(db_index=True, default='2022-11-12 23:50:00.000 +0530', verbose_name='start_at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='time_scale',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quaterly', 'Quaterly')], default='daily', max_length=100, verbose_name='time_scale'),
        ),
    ]
