# Generated by Django 4.0.5 on 2022-12-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soteria_atms", "0025_alter_job_end_at_alter_job_start_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="time_scale",
            field=models.CharField(
                choices=[("daily", "Daily"), ("monthly", "Monthly"), ("quarterly", "Quarterly")],
                default="daily",
                max_length=100,
                verbose_name="time scale",
            ),
        ),
    ]
